Templates
ndorfin/vanilla-pattern-library pull request #1
Opened 2024-06-24 06:18 UTC by yehudahsilberg

Creating templates

2024-06-24 07:03 UTC, ndorfin requested changes
Thanks for this Yehudah

I've put some comments on the `<form>` example.

Would you mind taking a deeper dive into the content and writing it out as is it in the mockups?
This will help us uncover more inconsistencies, but also identify faulty or missing patterns.

Cheers!

2024-06-24 07:03 UTC, ndorfin commented on src/_data/templates/location-lookup-form.yml
> +              google Recaptcha
Optional: Would you like to take a stab at including Google Recaptcha?

2024-06-24 08:43 UTC, yehudahsilberg commented on src/_data/templates/location-lookup-form.yml
> +    <div class="container" data-theme="rich" data-mode="location-lookup">
What field should I use here instead?

2024-06-26 06:52 UTC, ndorfin approved these changes
Good work Yehudah - Please go ahead and merge this.
Then, I'd suggest cloning this repo (rather than your fork) and working on this repo directly using feature/bugfix branches.

2024-06-26 06:52 UTC, ndorfin commented on src/_data/templates/location-lookup-form.yml
> +  <head>
This would produce some invalid HTML, as we can't have a `<head>` element in the `<body>` of the document. That's OK for now, we can remove it later.

2024-06-26 07:22 UTC, merged